name: Tests
on: [push, pull_request,workflow_dispatch]
jobs:
  router-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8. 1']
        phpunit-versions: ['latest']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.1'
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Update Composer
        run: sudo composer self-update --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: run tests
        run: vendor/bin/pest --coverage-clover ./clover.xml
      - name: run static analysis
        run: vendor/bin/phpstan analyse src --level 5
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
